### ISSUE TITLE
New version crashes when playing the old version on Steam Beta.  Need a mod downgrade?

### ISSUE THREAD

**Issue by Darkmatterx76** [DoctorFeelGoodMD/OxygenNotIncluded-Mods#9]
After the patch I downgraded to the Fast Friends version due to broken mods. Mod Updater mod had already updated this mode, but most from other modders still didn't work. Strangely enough, this mod now crashes the game for Fast Friends... Can I get a mod rollback? :/

**Comment by DoctorFeelGoodMD** [comment]
Hi there. 
All the historical mod files are uploaded on github. You can browse old updates and download them, but you'll have to manually add it the game rather than with Steam.

For last update (Feb 26), go here: https://github.com/DoctorFeelGoodMD/OxygenNotIncluded-Mods/tree/88ff79bbb5f51d9ee1d6de0ed36d6649f8417a4a/mods
Download the folder for the mod in question and place it unzipped in Documents/Klei/OxygenNotIncluded/Mods/Local. Then turn it on with the mod manager (stock one works fine) and the steam version off.
Local mod won't update on its own, so it will break again when you do eventually update the game, you'll have to delete it and go back to the steam one (or download new local file)
